### ISSUE TITLE
Savestate & Loadstate feature

### ISSUE THREAD

**Issue by ramdanirfox** [EKA2L1/EKA2L1#314] opened 2021-07-24 09:54 UTC
Would you mind to add save/load state feature? Is it possible?
i'm in doubt because even j2me emulator counterparts doesn't have such feature, but IDK the real reason in detail, it just say emulator limitations.
https://github.com/nikita36078/J2ME-Loader/issues/90

**Comment by ramdanirfox** [comment] 2021-07-24 10:01
By the way, thanks for such a great emulator!

**Comment by pent0** [comment] 2021-07-24 11:35
hi，this is a duplicate of #265 . If you search the issues and see one the same, dont open another.

 In this case, possible, but the code of the emulator still changes so frequently that your save state might be break each time you update, so not yet.

**Closed by pent0** 2021-07-24 11:35 UTC
