### ISSUE TITLE
N-Gage Emulator crashes on any app call!

### ISSUE THREAD

**Issue by msmoc** [EKA2L1/EKA2L1#267] opened 2021-03-25 10:23 UTC
**Describe the bug**
If I want to start any app after successful emulator setup, the emulator crashes every time from 'Create screen device' -> see attached log!
This error only occurs on my Windows 7 computer!

**To Reproduce**
1. Start 'eka2l1.exe'(after successful device installation)
2. Click on 'File'
3. Click on 'Launch apps'
3. Select any listet App

**Expected behavior**
If I run a copy (!) of the entire installation folder on a Windows 10 computer, the error does not occur!

**Screenshots**
![error](https://user-images.githubusercontent.com/81358180/112457238-d8933b00-8d5b-11eb-9b57-783532dbbdc8.png)

**Your PC or smartphone specs**
- Microsoft Windows 7 Pro 64 Bit SP1
- Intel Core 2 Quad CPU 3.00 GHz
- NVIDIA GeForce GT 730
- All available Microsoft Visual C++20XX Redistributable versions are installed. 
- Windows Update is up to date. 

**Your emulator configuration**
- N-Gage

**Log**
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/6203893/EKA2L1.log)

**Comment by pent0** [comment] 2021-03-25 11:09
A lot of apps are not able yet to run on N-Gage on emulator, only About and some games. To track them, please visit Compability repo

**Comment by pent0** [comment] 2021-03-25 11:09
For support, visit discord server

**Comment by msmoc** [comment] 2021-03-25 11:13
> A lot of apps are not able yet to run on N-Gage on emulator, only About and some games. To track them, please visit Compability repo

It does not matter (!) which app is started!
Even the apps that are supported, for example the BLZ Installer App....
There must be something outside of the emulator in my operating system that the emulator does not get along with.

**Comment by pent0** [comment] 2021-03-25 11:14
You have turned on all configurations. Please use the default configuration

**Comment by msmoc** [comment] 2021-03-25 11:18
> You have turned on all configurations. Please use the default configuration and give log again. You can gain the default configuration by delete the config.yml

What exactly do you mean by 'turned on all configurations'?
I have turned on everything especially for the log, so that the entries in the log are more accurate.
The crash also occurs with the default configruration.

**Comment by msmoc** [comment] 2021-03-25 11:20
> You have turned on all configurations. Please use the default configuration and give log again. You can gain the default configuration by delete the config.yml

[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/6204231/EKA2L1.log)

**Comment by pent0** [comment] 2021-03-25 11:34
> I have turned on everything especially for the log, so that the entries in the log are more accurate

If I need I will ask. No need for you to act on your own. A lot of lines are spam if turned on

**Comment by msmoc** [comment] 2021-03-25 11:35
> > I have turned on everything especially for the log, so that the entries in the log are more accurate
> 
> If I need I will ask. No need for you to act on your own. A lot of lines are spam if turned on

Sorry, it was only well meant

**Comment by pent0** [comment] 2021-03-25 11:37
I cant seems to find any trouble in the log, please provide:
- Where did you get the n-gage rom (is it from indonesia youtube source or so)
- Did you install it using raw dump method or use lazy method
I am unable to find whats wrong at the moment, sorry

**Comment by msmoc** [comment] 2021-03-25 11:44
> I cant seems to find any trouble in the log, please provide:
> 
> * Where did you get the n-gage rom (is it from indonesia youtube source or so)
> * Did you install it using raw dump method or use lazy method
> 
> I am unable to find whats wrong at the moment, sorry

I got the Symbian ROM from this site:
https://archive.org/details/symbian-os-roms

For device installation I have used the raw method

Important note
If I copy this emulation folder with all subfolders to another Windows 10 computer, then the error does not occur.
Therefore I think that it is not due to the emulator configuration.

**Comment by pent0** [comment] 2021-03-25 11:48
All right, make sure you do not open or insert any weird files to data folder. And put it in a place where emulator can access it without adminstator permissions

**Comment by pent0** [comment] 2021-03-25 11:50
I also will suggest to move your emulation colder to another drive. If it still not work, I will provide you with a debug build and you can generate a stack trace when a crash is encountered.

**Comment by msmoc** [comment] 2021-03-25 11:51
I have already copied the emulation folder to a FAT32 partition for troubleshooting purposes to rule out any permissions issues. The error still occurs.
Furthermore, from the ZIP & RAR archive files, I have disabled the run protection for files from the Internet before unpacking. The error remains.

**Comment by msmoc** [comment] 2021-03-25 11:57
Since the error always occurs during the screen build of the emulated N-Gage and no pixels are generated yet, it may have something to do with my NVIDIA GeForce GT 730 graphics card?
The driver is certified from Windows Update.

**Comment by msmoc** [comment] 2021-03-25 12:01
... and the last lines from the first LOG always read:
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\svc.cpp:1067 [Kernel]: Sending 12 sync to Fontbitmapserver
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\context.cpp:375 [Service.Track]: Calling IPC: Server::Disconnect, id: -2

**Comment by pent0** [comment] 2021-03-25 12:28
Please download EKA2L1 [this link](https://mega.nz/file/mrIkDTSA#62pgzfPLQ_oH3PcmWokqOfkogB9IW5w_HVlhgzgtq4o), and then reinstall your ROM and launch the emulator though this [method](https://stackoverflow.com/questions/10586122/windbg-to-create-dump-file-upon-crash) to create a stack trace, which will assist in debugging this issue. Thanks。

**Comment by msmoc** [comment] 2021-03-25 13:25
Thanks for the links.
I monitored the execution of eka2l1.exe via Windbg and exported the dump to a text file.
The error message at the end of the dump occurs when opening any app in the emulator.

[Windbg_dump.txt](https://github.com/EKA2L1/EKA2L1/files/6204952/Windbg_dump.txt)

**Comment by pent0** [comment] 2021-03-25 13:27
How can't a Core 2 Duo not support popcnt instruction? This is very sad, and is the cause of the crash

**Comment by msmoc** [comment] 2021-03-25 16:20
OK, then obviously my aging processor is too old.... 
That's at least a statement ;)
Then I don't need to test the installation any longer.
Thanks a lot for the time and the fast and extensive help!
Many greetings from Hanover, DE

ps. since I'm obviously the only one who has the problem with an outdated processor, the issue can be deleted ;)

**Comment by pent0** [comment] 2021-03-25 17:37
Its  ok. I will add a fallback, this is forcefully using an instrict to calculate the bit count. I do suggest you move on to newer processor, but I will try to fix it as soon as report back here. So keep this issue not deleted

**Comment by msmoc** [comment] 2021-03-26 09:28
Thanks for your feedback and the time invested in my hardware problem.
Good luck with the implementation. 
And of course I am always available as a "test candidate" if needed :)

**Comment by pent0** [comment] 2021-03-27 05:13
@msmoc Please check newest release, it should fix

**Comment by msmoc** [comment] 2021-03-27 10:07
YESSS!!!!

![2021-03-27_110426](https://user-images.githubusercontent.com/81358180/112717342-48d0c680-8eec-11eb-9266-3bfc1e28df9e.png)

Now, when the screen opens, content is also displayed - and more importantly, no crash!!!
Many THX for your quick support!!!

**Comment by pent0** [comment] 2021-03-27 12:44
Thank you, I'm gonna close the issue

**Closed by pent0** 2021-03-27 12:44 UTC
Labels: HCI, OS Issues: Windows
