### ISSUE TITLE
Long press is not supported in Android version, some items need long press operation(by Translation software）

### ISSUE THREAD

**Issue by Hokam-kejin** [EKA2L1/EKA2L1#219] opened 2020-11-07 02:23 UTC
I want this long press function. Can it be solved? thanks~

**Comment by pent0** [comment] 2020-11-07 02:28
我是中国人上比例比例?

Regardless, ok. I will pass this to android developer. Please specify the game and action to reproduce and test this behaviour.

**Comment by basecell** [comment] 2020-11-07 02:45
I found that some buttons on Android are triggered by key release, this makes these buttons unable to achieve long press events.

**Comment by pent0** [comment] 2020-11-07 02:55
Please provide example game and possible save file?

**Comment by basecell** [comment] 2020-11-07 03:00
7 Day, Unable to trigger long press attack on weapon.

**Comment by basecell** [comment] 2020-11-07 03:16
![Screenrecorder-2020-11-07-11-07-46-643](https://user-images.githubusercontent.com/14192199/98430740-9dfd6e80-20ea-11eb-8d24-92d2b5e95fbf.gif)

**Comment by basecell** [comment] 2020-11-07 03:22
To trigger the F key you need to press the button and then release it, but to trigger the arrow key you just need to press the button.

**Comment by pent0** [comment] 2020-11-07 04:03
Is it ok to provide save file for fast reproduce?

**Comment by basecell** [comment] 2020-11-07 04:11
> Is it ok to provide save file for fast reproduce?

How can I extract my saved file and send it to you in what way?

**Comment by basecell** [comment] 2020-11-07 05:09
I think the problem lies in the PC version. I copied the data directory to the PC version of eka2l1 and found the same problem. If possible, I am willing to provide my data directory.

**Comment by pent0** [comment] 2020-11-07 05:56
F key=fire key right? So the behaviour expected is: a press can do a normal attack, a hold can do charged attack right? Since you guys did not fill the issue form.

**Comment by basecell** [comment] 2020-11-07 06:21
> F key=fire key right? So the behaviour expected is: a press can do a normal attack, a hold can do charged attack right? Since you guys did not fill the issue form.

Yes it is.

**Comment by pent0** [comment] 2020-11-07 11:10
Hi, no matter what I have tried. I can't seems to trigger this. If possible, can you record me the long press attack with your hand on a real phone? Sorry for the inconvenience, if not possible it's also OK.

**Comment by basecell** [comment] 2020-11-07 11:31
> Hi, no matter what I have tried. I can't seems to trigger this. If possible, can you record me the long press attack with your hand on a real phone? Sorry for the inconvenience, if not possible it's also OK.
> 
> Addition comment: I tried to spawn more key event related, but it is still the same unfortunately.

How to do? By video?

**Comment by pent0** [comment] 2020-11-07 11:45
Yes. That's what I mean by "record".

**Comment by basecell** [comment] 2020-11-07 11:47
![国产3a大作《七夜》剧情通关全集（cooljazz解说）_P2247_42 29736487 flv_20201107_194235](https://user-images.githubusercontent.com/14192199/98440108-96ad8380-2131-11eb-9e53-c6a5b547064b.gif)

**Comment by pent0** [comment] 2020-11-07 11:49
Okay, thank you. Is there any special mechanism on it or just hold and no need two normal attack before?

**Comment by basecell** [comment] 2020-11-07 11:51
This is a clip that I found on the web, the meaning of the yellow word is as follows: "Press 5 to attack. Hold down the 5 key to use heavy attack".

**Comment by pent0** [comment] 2020-11-07 11:53
Thanks. I will keep you updated when I'm figuring out. I may have to reverse engineering the code.

**Comment by basecell** [comment] 2020-11-07 11:55
Because there is no real machine around me, So I can only guess that if you press the 5 button and lift it quickly, it will trigger a light attack; If you keep pressing the 5 button, a heavy attack will be triggered.

**Comment by Hokam-kejin** [comment] 2020-11-07 16:40
> 是。这就是我所说的“记录”。

bilibili Video link：https://www.bilibili.com/video/BV1gb411H7YY
start at 0:50,Press A to attack. Press and hold the A key to shoot

**Comment by pent0** [comment] 2020-11-07 17:00
Fix later. I know the reason.

**Comment by pent0** [comment] 2020-11-07 20:09
Check out  7e4f77b . Should fixed on both android and pc.

**Comment by basecell** [comment] 2020-11-08 01:59
> Check out [bba59b7](https://github.com/EKA2L1/EKA2L1/commit/bba59b70821cd5b24f811690724c0432ff73505b). Should fixed on both android and pc. You can wait for release or click on the link and click on the 。/ v and choose your platform to download.

I tested the latest two versions: bba59b70, e2485158, including PC and Android platforms, and found that the problem still exists.

**Comment by Hokam-kejin** [comment] 2020-11-08 02:57
Thanks for your hard work！ I test the bba59b7,5 key is ok,but F key still can't use it like this

![ff471d9401fd1220ffb9b50a050cd98d~1](https://user-images.githubusercontent.com/74083017/98455874-3bbb7100-21b1-11eb-8829-bd3a3e564dd5.gif)

**Comment by pent0** [comment] 2020-11-08 04:36
basecell, you use enter or 5. 5 should definitely be ok.

**Comment by pent0** [comment] 2020-11-08 04:45
F key fixed. Wait for newest release on github. If you have any errors dont hesitate to use translation software to open issue on github, or ask someone in the community to assist you on translating.

**Comment by basecell** [comment] 2020-11-08 05:19
It worked. Thanks.

**Closed** 2020-11-08 05:37 UTC
